config/routes.rb
Rails.application.routes.draw do
  
  resources :political_leadership, only: []  do
    collection do
      get :provinces_and_districts
    end

    member do
      get :districts
      get :constituencies
    end
  end

  namespace :admin do
    get 'dashboard/index'
  end
  get 'contactus/index'
  devise_for :users
  
  namespace :admin do
    resources :members
    resources :uploaders
    resources :team_members
    resources :responsibilities
    resources :responsibility_sessions
  end
  
  resources :members do
    collection do
      get :districts
      get :area
      get :units
      get :check_cnic
    end
  end

  resources :team, only: [:index, :show] 

  get 'form/index'
  get 'form/show'
  get 'aboutus/index'
  get 'news/index'
  get 'news/show'
  get 'home/index'
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assembly_ji.rb
class AssemblyJi < ApplicationRecord
	belongs_to :district_ji
	has_many :candidate_jis, dependent: :destroy

  enum constituencies: [:na, :pp]
end

app/models/candidate_ji.rb
class CandidateJi < ApplicationRecord
	belongs_to :assembly_ji
end

app/models/district.rb
class District < ApplicationRecord
	belongs_to :province
	has_many :local_government_structures
	validates :title, uniqueness: true
end

app/models/district_ji.rb
class DistrictJi < ApplicationRecord
	belongs_to :province_ji
	has_many :assembly_jis, dependent: :destroy
end

app/models/member.rb
class Member < ApplicationRecord
	belongs_to :area, polymorphic: true
end

app/models/province.rb
class Province < ApplicationRecord
	has_many :districts
	validates :title, uniqueness: true
end

app/models/province_ji.rb
class ProvinceJi < ApplicationRecord
	has_many :district_jis, dependent: :destroy
end

app/models/responsibility.rb
class Responsibility < ApplicationRecord
	has_many :responsibility_sessions, dependent: :destroy
end

app/models/responsibility_session.rb
class ResponsibilitySession < ApplicationRecord
	belongs_to :team_member
	belongs_to :responsibility
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
	has_many :responsibility_sessions, dependent: :destroy
	has_one_attached :image
end

app/models/unit.rb
class Unit < ApplicationRecord
	belongs_to :local_government_structure
	has_many :members, as: :area
  enum unit_name: [:union_council, :ward, :village_council, :neighbourhood_council]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  enum role: [:admin, :user]
end

app/controllers/admin/responsibility_sessions_controller.rb
class Admin::ResponsibilitySessionsController < Admin::BaseController
	
	before_action :find_params, only: [:edit, :update, :show, :destroy]
	
	def index
    @responsibility_sessions = ResponsibilitySession.all
  end

  def new
    @responsibility_session = ResponsibilitySession.new
  end

  def create
    @responsibility_session = ResponsibilitySession.create(responsibilty_session_params)
    if @responsibility_session.save!
      redirect_to admin_responsibility_sessions_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @responsibility_session.update(responsibilty_session_params)
    redirect_to admin_responsibility_sessions_path
  end

  def show
  end

  def destroy
    @responsibility_session.destroy
    redirect_to admin_responsibility_sessions_path
  end

  private

  def responsibilty_session_params
    params.require(:responsibility_session).permit(:year, :start_date, :end_date, :team_member_id, :responsibility_id)
  end

  def find_params
    @responsibility_session = ResponsibilitySession.find(params[:id])
  end

end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/admin/responsibility_sessions_helper.rb
module Admin::ResponsibilitySessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def toastr_flash
      flash.each_with_object([]) do |(type, message), flash_messages|
        type = 'success' if type == 'notice'
        type = 'error' if type == 'alert'
        text = "<script>toastr.#{type}('#{message}', '', { closeButton: true })</script>"
        flash_messages << text.html_safe if message
      end.join("\n").html_safe
    end
end

app/helpers/form_helper.rb
module FormHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/admin/responsibility_sessions/_form.html.erb
<% url = params[:action] == 'edit' ? admin_responsibility_session_path : admin_responsibility_sessions_path %>
<%= form_for @responsibility_session, url: url do |f| -%>
	<div class="row">
		<%= f.label :start_date, class:"col-sm-2"-%>
		<%= f.datetime_field :start_date, class:"col-sm-3" -%>
	</div>
	<div class="row">
		<%= f.label :end_date, class:"col-sm-2"-%>
		<%= f.datetime_field :end_date, class:"col-sm-3" -%>
	</div>
	<div class="row">
		<%= f.select :team_member_id, options_for_select(TeamMember.all.map { |team_member| [team_member.name, team_member.id] },:selected => f.object.team_member_id) -%><br>
	</div>
		<div class="row">
		<%= f.select :responsibility_id, options_for_select(Responsibility.all.map { |res| [res.title, res.id] },:selected => f.object.responsibility_id) -%><br>
	</div>
	<%= f.submit %>
<% end -%>

app/views/admin/responsibility_sessions/edit.html.erb
<%= render 'form' %>

app/views/admin/responsibility_sessions/index.html.erb
<section class="pp-section">
	<div class="container-fluid">
    <div class="row">
      <div class="col-sm-12 text-right">
        <%= link_to "Add Responsibilty Session", new_admin_responsibility_session_path, class: "btn btn-primary"%>                
      </div>
    </div>
  </div>
  <div class="container ">  
    <div class="row">
      <div class="col">
        <div class="table-responsive">
			    <table class="table table-bordered">
			      <thead class="bg-dark-blue">
			        <tr>
			          <th scope="col">#</th>
			          <th scope="col">Team Member</th>
			          <th scope="col">Responsibilty</th>
			          <th scope="col">Start Date</th>
			          <th scope="col">End Date</th>
			          <th scope="col">Action</th>
			        </tr>
			      </thead>
			      <tbody>
			        <% @responsibility_sessions.each do |res_session| %>
			        	<tr>
					        <th scope="row"><%= res_session.id %></th>
					        <th scope="row"><%= res_session.team_member.name %></th>
					        <th scope="row"><%= res_session.responsibility.title %></th>
					        <td scope="row"><%= res_session.start_date %></td>
					        <td scope="row"><%= res_session.end_date %></td>
					        <td>
					        <div class="d-inline  title-action-btn">
					        	<%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_admin_responsibility_session_path(res_session.id) %>
	            			<%= button_to  admin_responsibility_session_path(res_session.id), method: :delete  do %>
	                		<span class="fa fa-trash"></span>
	            			<% end %>
	            		</div>
					        </td>
					      </tr>
			        <% end %>
			      </tbody>
			    </table>
			  </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/responsibility_sessions/new.html.erb
<%= render 'form' %>