config/routes.rb
Rails.application.routes.draw do
  
  resources :political_leadership, only: []  do
    collection do
      get :provinces_and_districts
    end

    member do
      get :districts
      get :constituencies
    end
  end

  namespace :admin do
    get 'dashboard/index'
  end
  get 'contactus/index'
  devise_for :users
  
  namespace :admin do
    resources :members
    resources :uploaders
    resources :team_members
    resources :responsibilities
    resources :responsibility_sessions
  end
  
  resources :members do
    collection do
      get :districts
      get :area
      get :units
      get :check_cnic
    end
  end

  resources :team, only: [:index, :show] 

  get 'form/index'
  get 'form/show'
  get 'aboutus/index'
  get 'news/index'
  get 'news/show'
  get 'home/index'
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assembly_ji.rb
class AssemblyJi < ApplicationRecord
	belongs_to :district_ji
	has_many :candidate_jis, dependent: :destroy

  enum constituencies: [:na, :pp]
end

app/models/candidate_ji.rb
class CandidateJi < ApplicationRecord
	belongs_to :assembly_ji
end

app/models/district.rb
class District < ApplicationRecord
	belongs_to :province
	has_many :local_government_structures
	validates :title, uniqueness: true
end

app/models/district_ji.rb
class DistrictJi < ApplicationRecord
	belongs_to :province_ji
	has_many :assembly_jis, dependent: :destroy
end

app/models/member.rb
class Member < ApplicationRecord
	belongs_to :area, polymorphic: true
end

app/models/province.rb
class Province < ApplicationRecord
	has_many :districts
	validates :title, uniqueness: true
end

app/models/province_ji.rb
class ProvinceJi < ApplicationRecord
	has_many :district_jis, dependent: :destroy
end

app/models/responsibility.rb
class Responsibility < ApplicationRecord
	has_many :responsibility_sessions, dependent: :destroy
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
	has_many :responsibility_sessions, dependent: :destroy
	has_one_attached :image
end

app/models/unit.rb
class Unit < ApplicationRecord
	belongs_to :local_government_structure
	has_many :members, as: :area
  enum unit_name: [:union_council, :ward, :village_council, :neighbourhood_council]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  enum role: [:admin, :user]
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def toastr_flash
      flash.each_with_object([]) do |(type, message), flash_messages|
        type = 'success' if type == 'notice'
        type = 'error' if type == 'alert'
        text = "<script>toastr.#{type}('#{message}', '', { closeButton: true })</script>"
        flash_messages << text.html_safe if message
      end.join("\n").html_safe
    end
end

app/helpers/form_helper.rb
module FormHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/layouts/shared/_admin-nav.html.erb
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/home/index" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>

app/views/layouts/shared/_admin_footer.html.erb
<footer class="main-footer">
  <strong>Copyright &copy; 2023 <a href="#">JIyouth </a>.</strong>
  All rights reserved.
  <div class="float-right d-none d-sm-inline-block">
    <b>Designed by</b> <a href="#">Devcache pvt ltd.</a>
  </div>
</footer>

app/views/layouts/shared/_admin_header.html.erb
<% if current_user.admin?%>
  <!-- Admin NavBar -->
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light position-relative">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
      </ul>
      <p style="position: absolute; left: 43%; font-weight: bolder; font-size: 19px; top: 11px;"><%= current_user.email %></p>
      <!-- Right navbar links -->
      <ul class="navbar-nav ml-auto">
        <li class='nav-item'><%= link_to destroy_user_session_path, class:'nav-link' do %>
          <i class="fa fa-power-off"></i>
          <% end -%>
        </li>
      </ul>
    </nav>
  <!-- end Admin NavBar -->

  <% end %>

app/views/layouts/shared/_desktop-slider.html.erb
<!-- <section>
  <div class="container">
    <div class="row align-items-center justify-content-center">
      <div class="col-sm-12">
        
      </div>
    </div>
  </div>
</section> -->

<div class="slideshow-container position-relative">
  <div class="mySlides">
    <img src="/assets/slides/siraj_sab.svg" style="width: 100%" />
  </div>

  <div class="mySlides">
    <img src="/assets/slides/russel_bahi.svg" style="width: 100%" />
  </div>

  <a class="prev" onclick="plusSlides(-1)"></a>
  <a class="next" onclick="plusSlides(1)"></a>

  <div class="circle-controle" style="text-align: center">
    <span class="dot" onclick="currentSlide(1)"></span>
    <span class="dot" onclick="currentSlide(2)"></span>

  </div>
</div>

<script>
  let slideIndex = 1;
  showSlides(slideIndex);

  function plusSlides(n) {
    showSlides((slideIndex += n));
  }

  setInterval(auto_next_slide, 2000);

function auto_next_slide(){ plusSlides(1) }

  function currentSlide(n) {
    showSlides((slideIndex = n));
  }

  function showSlides(n) {
    let i;
    let slides = document.getElementsByClassName("mySlides");
    let dots = document.getElementsByClassName("dot");
    if (n > slides.length) {
      slideIndex = 1;
    }
    if (n < 1) {
      slideIndex = slides.length;
    }
    for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
    }
    for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex - 1].style.display = "block";
    dots[slideIndex - 1].className += " active";
  }
  

  
</script>

app/views/layouts/shared/_footer.html.erb
<footer id="footer" class="mt-0">
        <div class="container my-4">
          <div class="row py-5">
            <div class="col-md-6 col-lg-3 mb-5 mb-lg-0">
              <h5
                class="text-5 text-transform-none font-weight-semibold text-color-light mb-4"
              >
                Contact Details
              </h5>
              <p class="text-4 mb-0">Mansoora, Multan Road,</p>
              <p class="text-4 mb-0"> Lahore, Pakistan.</p>
            </div>
            <div class="col-md-6 col-lg-3 mb-5 mb-lg-0">
              <h5
                class="text-5 text-transform-none font-weight-semibold text-color-light mb-4"
              >
                Opening Hours
              </h5>
              <p class="text-4 mb-0">
                7 Days :
                <span class="text-color-light">24 / 7</span>
              </p>
              <p class="text-4 mb-0 d-none">
                Saturday:
                <span class="text-color-light">9:30 am to 1:00 pm</span>
              </p>
              <p class="text-4 mb-0 d-none">
                Sunday: <span class="text-color-light">Closed</span>
              </p>
            </div>
            <div class="col-md-6 col-lg-3 mb-5 mb-lg-0">
              <h5
                class="text-5 text-transform-none font-weight-semibold text-color-light mb-4"
              >
                Call Us Now
              </h5>
              <p class="text-7 text-color-light font-weight-bold mb-2 d-none">
                <a
                  href="tel:+924235252144"
                  class="text-decoration-none text-color-light"
                  >+92-42-35252144  </a
                >
              </p>
              <p class="text-4 mb-0">
                
                <span class="text-color-light">
                  <a
                    href="tel:+924235252144"
                    class="text-decoration-none text-color-light"
                    >+92-42-35252144  </a
                  >
                </span>
              </p>
            </div>
            <div class="col-md-6 col-lg-3">
              <h5
                class="text-5 text-transform-none font-weight-semibold text-color-light mb-4"
              >
                Social Media
              </h5>
              <ul class="footer-social-icons social-icons m-0">
                <li class="social-icons-facebook">
                  <a
                    href="https://web.facebook.com/JIYouth.Pk?_rdc=1&_rdr"
                    target="_blank"
                    title="Facebook"
                    ><i class="fab fa-facebook-f text-2"></i
                  ></a>
                </li>
                <li class="social-icons-twitter">
                  <a
                    href="https://www.instagram.com/jiyouth.pk/"
                    target="_blank"
                    title="instagram"
                    ><i class="fab fa-instagram text-2"></i
                  ></a>
                </li>

                <li class="social-icons-twitter">
                  <a
                    href="https://twitter.com/JIYouthOfficial"
                    target="_blank"
                    title="Twitter"
                    ><i class="fab fa-twitter text-2"></i
                  ></a>
                </li>
                <li class="social-icons-linkedin">
                  <a
                    href="https://www.youtube.com/channel/UCwvtJYWaFgeRUQtjeh9d2Cg"
                    target="_blank"
                    title="Youtube"
                    ><i class="fab fa-youtube text-2"></i
                  ></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="container">
          <div class="footer-copyright footer-copyright-style-2 pb-4">
            <div class="py-2">
              <div class="row py-4">
                <div
                  class="col d-flex align-items-center justify-content-center mb-4 mb-lg-0"
                >
                  <p>© Copyright 2023. All Rights Reserved.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </footer>

app/views/layouts/shared/_header.html.erb
<header
  id="header"
  data-plugin-options="{'stickyEnabled': true, 'stickyEnableOnBoxed': true, 'stickyEnableOnMobile': true, 'stickyStartAt': 148, 'stickySetTop': '-148px', 'stickyChangeLogo': true}"
>
  <div class="header-body border-color-primary border-top-0 box-shadow-none">
    <div class="header-top header-top-default border-bottom-0 border-top-0">
      <div class="container">
        <div class="header-row py-2">
          <div class="header-column justify-content-start">
            <div class="header-row">
              <nav class="header-nav-top">
                <ul class="nav nav-pills text-uppercase text-2">
                  <li class="nav-item nav-item-anim-icon">
                    <a class="nav-link ps-0" href="#"
                      ><i class="fas fa-angle-right"></i> About Us</a
                    >
                  </li>
                  <li class="nav-item nav-item-anim-icon">
                    <a class="nav-link" href="#"  
                      ><i class="fas fa-angle-right"></i> Contact Us</a
                    >
                  </li>
                </ul>
              </nav>
            </div>
          </div>
          <div class="header-column justify-content-end">
            <div class="header-row">
              <ul
                class="header-social-icons social-icons d-none d-sm-block social-icons-clean"
              >
                <li class="social-icons-facebook">
                  <a
                    href="https://www.instagram.com/jiyouth.pk/"
                    target="_blank"
                    title="Instagram"
                    ><i class="fab fa-instagram"></i
                  ></a>
                </li>
                <li class="social-icons-twitter">
                  <a
                    href="https://twitter.com/JIYouthOfficial"
                    target="_blank"
                    title="Twitter"
                    ><i class="fab fa-twitter"></i
                  ></a>
                </li>

                <li class="social-icons-facebook">
                  <a
                    href="https://web.facebook.com/JIYouth.Pk?_rdc=1&_rdr"
                    target="_blank"
                    title="Facebook"
                    ><i class="fab fa-facebook-f"></i
                  ></a>
                </li>
                <li class="social-icons-linkedin">
                  <a
                    href="https://www.youtube.com/channel/UCwvtJYWaFgeRUQtjeh9d2Cg"
                    target="_blank"
                    title="Youtube"
                    ><i class="fab fa-youtube"></i
                  ></a>
                </li>

                <% if current_user.present? && current_user.admin? %>
                  <li>
                    <a
                      href="/admin/dashboard/index"
                      <%# target="_blank" %>
                      title="Dashboard"
                      ><i class="fa fa-clipboard"></i
                    ></a>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="header-container container z-index-2">
      <div class="header-row py-2">
        <div class="header-column">
          <div class="header-row">
            <div class="header-logo header-logo-sticky-change">
              <a href="/">
              <%#= image_tag "jiyouthlogo.png", class:"header-logo-sticky opacity-0", alt:"JiYouth"%>
                <img
                  class="header-logo-sticky opacity-0"
                  alt="JiYouth"
                  width="100"
                  height="48"
                  data-sticky-width="89"
                  data-sticky-height="43"
                  data-sticky-top="88"
                  src="/assets/jiyouthlogo.png"
                />
                <img
                  class="header-logo-non-sticky opacity-0"
                  alt="JiYouth"

                  src="/assets/jiyouthlogo.png"
                /> 
              </a>
            </div>
          </div>
        </div>
        <div class="header-column justify-content-end">
          <div class="header-row">
            <ul class="header-extra-info d-flex align-items-center">
              <li class="d-none d-sm-inline-flex">
                <div class="header-extra-info-icon">
                  <i
                    class="far fa-envelope text-color-primary text-4 position-relative bottom-2"
                  ></i>
                </div>
                <div class="header-extra-info-text">
                  <label>SEND US AN EMAIL</label>
                  <strong
                    ><a
                      href="mailto:info@jiyouth.pk"
                      class="text-decoration-none text-color-hover-primary"
                      >info@jiyouth.org</a
                    ></strong
                  >
                </div>
              </li>
              <li>
                <div class="header-extra-info-icon">
                  <i
                    class="fab fa-whatsapp text-color-primary text-4 position-relative bottom-1"
                  ></i>
                </div>
                <div class="header-extra-info-text">
                  <label>CALL US NOW</label>
                  <strong
                    ><a
                      href="tel:+924235252144  "
                      class="text-decoration-none text-color-hover-primary"
                      >+92-42-35252144
                    </a></strong
                  >
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div
      class="header-nav-bar bg-primary"
      data-sticky-header-style="{'minResolution': 991}"
      data-sticky-header-style-active="{'background-color': 'transparent'}"
      data-sticky-header-style-deactive="{'background-color': '#0088cc'}"
    >
      <div class="container">
        <div class="header-row">
          <div class="header-column">
            <div class="header-row justify-content-end">
              <div
                class="header-nav header-nav-force-light-text justify-content-start py-2 py-lg-3"
                data-sticky-header-style="{'minResolution': 991}"
                data-sticky-header-style-active="{'margin-left': '135px'}"
                data-sticky-header-style-deactive="{'margin-left': '0'}"
              >
                <div
                  class="header-nav-main header-nav-main-effect-1 header-nav-main-sub-effect-1"
                >
                  <nav class="custome-handle collapse">
                    <ul class="nav nav-pills" id="mainNav">
                      <li class="dropdown dropdown-full-color dropdown-light">
                        <a href="/" class="dropdown-item active">
                          Home
                        </a>
                      </li>

                      <li class="dropdown dropdown-full-color dropdown-light">
                        <a class="dropdown-item"> About Us </a>
                      </li>

                      <li class="dropdown dropdown-full-color dropdown-light">
                        <a class="dropdown-item"> Activities </a>
                      </li>

                      <li class="dropdown dropdown-full-color dropdown-light">
                        <a class="dropdown-item"> Events </a>
                      </li>

                      <li class="dropdown dropdown-full-color dropdown-light">
                        <a class="dropdown-item"> Media </a>
                      </li>

                      <li class="dropdown dropdown-full-color dropdown-light">
                        <a class="dropdown-item"> News </a>
                      </li>

                      <li class="dropdown dropdown-full-color dropdown-light">
                        <a class="dropdown-item"> Contact </a>
                      </li>

                      <li class="dropdown dropdown-full-color dropdown-light">
                        <%= link_to "Political Leadership",provinces_and_districts_political_leadership_index_path , class: " Political Leadership "%>
                      </li>
                      
                    </ul>
                  </nav>
                </div>
                <button
                  class="btn header-btn-collapse-nav my-2"
                >
                  <i class="fas fa-bars"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>


<script>
$(document).ready(function(){
  $("body").on("click", ".header-btn-collapse-nav", function(e){
    if ($('.header-nav-main nav').hasClass("show")){
      $('.header-nav-main nav').removeClass("show")
      $('.header-nav-main nav').addClass("closed")

      $('html').removeClass('mobile-menu-opened');

			 		$('.header-body').animate({
				 		height: ($('.header-body').outerHeight() - $('.header-nav-main nav').outerHeight(true))
				 	}, function(){
				 		$(this).height('auto');
				 	});
    } else {
      $('.header-nav-main nav').removeClass("closed")
      $('.header-nav-main nav').addClass("show")
      $('html').addClass('mobile-menu-opened');

			 		$('.header-body').animate({
				 		height: ($('.header-body').outerHeight() + $('.header-nav-main nav').outerHeight(true)) + 10
				 	});

				 	//Header Below Slider / Header Bottom Slider - Scroll to menu position
				 	if( $('#header').is('.header-bottom-slider, .header-below-slider') && !$('html').hasClass('sticky-header-active') ) {
				 		self.scrollToTarget( $('#header'), 0 );
				 	}
    } 
  })

});
</script>