config/routes.rb
Rails.application.routes.draw do
  
  resources :political_leadership, only: []  do
    collection do
      get :provinces_and_districts
    end

    member do
      get :districts
      get :constituencies
    end
  end

  namespace :admin do
    get 'dashboard/index'
  end
  get 'contactus/index'
  devise_for :users
  
  namespace :admin do
    resources :members
    resources :uploaders
    resources :team_members
    resources :responsibilities
    resources :responsibility_sessions
  end
  
  resources :members do
    collection do
      get :districts
      get :area
      get :units
      get :check_cnic
    end
  end

  resources :team, only: [:index, :show] 

  get 'form/index'
  get 'form/show'
  get 'aboutus/index'
  get 'news/index'
  get 'news/show'
  get 'home/index'
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assembly_ji.rb
class AssemblyJi < ApplicationRecord
	belongs_to :district_ji
	has_many :candidate_jis, dependent: :destroy

  enum constituencies: [:na, :pp]
end

app/models/candidate_ji.rb
class CandidateJi < ApplicationRecord
	belongs_to :assembly_ji
end

app/models/district.rb
class District < ApplicationRecord
	belongs_to :province
	has_many :local_government_structures
	validates :title, uniqueness: true
end

app/models/district_ji.rb
class DistrictJi < ApplicationRecord
	belongs_to :province_ji
	has_many :assembly_jis, dependent: :destroy
end

app/models/member.rb
class Member < ApplicationRecord
	belongs_to :area, polymorphic: true
end

app/models/province.rb
class Province < ApplicationRecord
	has_many :districts
	validates :title, uniqueness: true
end

app/models/province_ji.rb
class ProvinceJi < ApplicationRecord
	has_many :district_jis, dependent: :destroy
end

app/models/responsibility.rb
class Responsibility < ApplicationRecord
	has_many :responsibility_sessions, dependent: :destroy
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
	has_many :responsibility_sessions, dependent: :destroy
	has_one_attached :image
end

app/models/unit.rb
class Unit < ApplicationRecord
	belongs_to :local_government_structure
	has_many :members, as: :area
  enum unit_name: [:union_council, :ward, :village_council, :neighbourhood_council]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  enum role: [:admin, :user]
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < Admin::BaseController
    def index
        @members = Member.all
    end
end

app/controllers/form_controller.rb
class FormController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def create
    unit =  if params["unit"].present?
              Unit.find_by_id(params["unit"])
            else
              LocalGovernmentStructure.find_by_id(params[:local_govt_structure_id])
            end
    member = unit.members.new(
                      father_name: params[:father_name],
                      name: params[:name], email: params[:email],
                      phone: params[:phone], cnic: params[:cnic]
                    )
    if member.save
      flash[:success] = "#{member.name} with CNIC no #{member.cnic} Registered Successfully "
      redirect_to root_path
    else
      flash[:error] = "#{member.name} with CNIC no #{member.cnic} Not Registered"
      redirect_to new_member_path
    end
  end

  def check_cnic
    @member = Member.find_by_cnic(params[:cnic])
    respond_to do |format|
      format.js
    end
  end

  def districts
    province = Province.find_by_id(params[:id])
    @districts = province.present? ? province.districts : nil
      respond_to do |format|
        format.js
      end 
  end

  def area
    district = District.find_by_id(params[:id])
    @areas = district.present? ? district.local_government_structures : nil
      respond_to do |format|
          format.js
      end 
  end

  def units
    area = LocalGovernmentStructure.find_by_id(params[:id])
    @units = area.present? ? area.units : nil
      respond_to do |format|
          format.js
      end 
  end

end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def toastr_flash
      flash.each_with_object([]) do |(type, message), flash_messages|
        type = 'success' if type == 'notice'
        type = 'error' if type == 'alert'
        text = "<script>toastr.#{type}('#{message}', '', { closeButton: true })</script>"
        flash_messages << text.html_safe if message
      end.join("\n").html_safe
    end
end

app/helpers/form_helper.rb
module FormHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/members/_area.html.erb
<%= select_tag('local_govt_structure_id', options_for_select(areas.map{|p| [p.title, p.id]}), prompt: 'Select Area', class:"form-select my-select-tag form-select-lg select-area") %>

<script>
  $(".select-area").on('change',function(){
    $.ajax({
      type: 'GET',
      dataType: 'script',
      url: '/members/units',
      data: {id: $(this).val()},
    });
  });
	
</script>

app/views/members/_districts.html.erb
<%= select_tag('district', options_for_select(districts.map{|p| [p.title, p.id]}), prompt: 'Select District', class:"form-select my-select-tag form-select-lg select-district") %>

<script>
  $(".select-district").on('change',function(){
    $.ajax({
      type: 'GET',
      dataType: 'script',
      url: '/members/area',
      data: {id: $(this).val()},
    });
  });
	
</script>

app/views/members/_empty_area.html.erb
<select class="form-select my-select-tag form-select-lg" disabled>
  <option value="" disabled selected>Select Area</option>
</select>

app/views/members/_empty_district.html.erb
<select class="form-select my-select-tag form-select-lg" disabled>
  <option value="" disabled selected>Select District</option>
</select>

app/views/members/_empty_unit.html.erb
<label for="units">Councils <span class="text-danger"> *</span></label>
<select class="form-select my-select-tag form-select-lg" disabled>
  <option value="" disabled selected>Select Council</option>
</select>

app/views/members/_units.html.erb
<label for="units">Councils <span class="text-danger"> *</span></label>
<%= select_tag('unit', options_for_select((units || []).map{|p| [p.title, p.id]}), prompt: 'Select Unit', class:"form-select my-select-tag form-select-lg select-unit") %>

app/views/members/area.js.erb
<% if @areas != nil %>
	$('#district_area').html("<%= escape_javascript(render partial: 'area', locals: { areas: @areas } ) %>")
<% else %>
	$('#district_area').html("<%= escape_javascript(render partial: 'empty_area' ) %>")
<% end %>

$('#area_unit').html("<%= escape_javascript(render partial: 'empty_unit' ) %>")
$("#nextBtn").prop('disabled', true);

app/views/members/check_cnic.js.erb
<% if @member.present? %>
	$('.cnic-alert').html('Cnic Already Exist')
<% else %>
	$('.cnic-alert').html('')
	$("#nextBtn").prop('disabled', false);
<% end %>

app/views/members/districts.js.erb
<% if @districts != nil %>
	$('#province_district').html("<%= escape_javascript(render partial: 'districts', locals: { districts: @districts } ) %>")
<% else %>
	$('#province_district').html("<%= escape_javascript(render partial: 'empty_district') %>")
<% end %>

$('#district_area').html("<%= escape_javascript(render partial: 'empty_area' ) %>")

$('#area_unit').html("<%= escape_javascript(render partial: 'empty_unit' ) %>")

$("#nextBtn").prop('disabled', true);

app/views/members/new.html.erb
<section class="multi-step-form">
  <%= form_tag( members_path, :method => :post, id: 'signUpForm'  ) do%>

    <!-- start step indicators -->
    <div class="form-header d-flex mb-4">
      <span class="stepIndicator">CNIC</span>
      <span class="stepIndicator">Area</span>
      <span class="stepIndicator">Detail</span>
    </div>
    <!-- end step indicators -->

    <!-- step one -->
    <div class="step">
      <p class="text-center mb-4 notify-message">
      For now, only Punjab and KPK members can be added through this form. We are collecting the data for other provinces so they will be available soon.
      </p>
      <div class="mb-3">
        <label for="cnic"
          >Enter National ID # <span class="text-danger"> (xxxxx-xxxxxx-x)*</span></label>
        <div class="cnic-alert" style="color: darkred;"></div>
        <input type="text" id="cnic"  placeholder="XXXXX-XXXXXXX-X"  name="cnic" required="true" minlength="15" maxlength="15" >
      </div>
    </div>

    <!-- step two -->
    <div class="step">
      <div class="mb-3">
        <label for="exampleInputEmail1"
          >Province <span class="text-danger"> *</span></label>
        <%= select_tag('province', options_for_select(Province.all.map{|p| [p.title, p.id]}), prompt: 'Select Province', class:"form-select my-select-tag form-select-lg select-province", :required => true) %>
      </div>

      <div class="mb-3">
        <label for="selectDistrict">District <span class="text-danger"> *</span></label>
        <div id="province_district">
          <select class="form-select my-select-tag form-select-lg" disabled>
            <option value="" disabled selected>Select District</option>
          </select>
        </div>
      </div>

      <div class="mb-3">
        <label for="district_area">Area (Local Govt Structure)<span class="text-danger"> *</span></label>
        <div id="district_area">
          <select class="form-select my-select-tag form-select-lg" disabled>
            <option value="" disabled selected>Select Area</option>
          </select>
        </div>
      </div>

      <div class="mb-3 main" id="area_unit">
        <label for="units">Councils <span class="text-danger"> *</span></label>
        <select class="form-select my-select-tag form-select-lg" disabled>
          <option value="" disabled selected>Select Council</option>
        </select>
      </div>

    </div>

    <!-- step three -->

     <div class="step">
      <p class="text-center mb-4">Personal Inforamtion & presence on the social network</p>
      <div class="mb-3">
        <label for="inputName">Name <span class="text-danger"> *</span></label>
        <%= text_field_tag :name, "", class: 'form-control', placeholder: 'Name' %>
      </div>

      <div class="mb-3">
        <label for="inputName">Father Name <span class="text-danger"> *</span></label>
        <%= text_field_tag :father_name, "", class: 'form-control', placeholder: 'Father Name' %>
      </div>

      <div class="mb-3">
        <label for="inputEmail">Email Address<span class="text-danger"> *</span></label>
        <%= text_field_tag :email, "", class: 'form-control', placeholder: 'Email' %>

      </div>

      <div class="mb-3">
        <label for="forPhone">Phone # <span class="text-danger"> *</span></label>
        <%= text_field_tag :phone, "", class: 'form-control', placeholder: 'Phone' %>
      </div>


    </div>

    <!-- start previous / next buttons -->
    <div class="form-footer d-flex">
      <button type="button" id="prevBtn" onclick="nextPrev(-1)">
        Previous
      </button>
      <button type="button" id="nextBtn" onclick="nextPrev(1)" disabled>Next</button>
    </div>
    <!-- end previous / next buttons -->
  <% end -%>
</section>

<div></div>

<%# <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/3/jquery.inputmask.bundle.js"></script> %>
<script>

  $("#cnic").on('keyup', function() {
    cnic_no = $(this).val();
    cnic_no_regex = /^[0-9+]{5}-[0-9+]{7}-[0-9]{1}$/;
    if(cnic_no_regex.test(cnic_no))
    {
        //check cnic exists?
            $.ajax({
              type: 'GET',
              dataType: 'script',
              url: '/members/check_cnic',
              data: {cnic: cnic_no},
            });
    }
    else {
      $("#nextBtn").prop('disabled', true);
    }
  })  

  var currentTab = 0; // Current tab is set to be the first tab (0)
  showTab(currentTab); // Display the current tab

  function showTab(n) {
    // This function will display the specified tab of the form...
    var x = document.getElementsByClassName("step");
    x[n].style.display = "block";
    //... and fix the Previous/Next buttons:
    if (n == 0) {
      document.getElementById("prevBtn").style.display = "none";
    } else {
      document.getElementById("prevBtn").style.display = "inline";
    }
    if (n == x.length - 1) {
      document.getElementById("nextBtn").innerHTML = "Submit";
    } else {
      document.getElementById("nextBtn").innerHTML = "Next";
    }
    //... and run a function that will display the correct step indicator:
    fixStepIndicator(n);
  }

  function nextPrev(n) {
    // This function will figure out which tab to display
    var x = document.getElementsByClassName("step");
    // Exit the function if any field in the current tab is invalid:
    if (n == 1 && !validateForm()) return false;
    // Hide the current tab:
    x[currentTab].style.display = "none";
    // Increase or decrease the current tab by 1:
    currentTab = currentTab + n;
    // if you have reached the end of the form...
    if (currentTab >= x.length) {
      // ... the form gets submitted:
      document.getElementById("signUpForm").submit();
      return false;
    }
    // Otherwise, display the correct tab:
    showTab(currentTab);
  }

  function validateForm() {
    // This function deals with validation of the form fields
    var x,
      y,
      i,
      valid = true;
    x = document.getElementsByClassName("step");
    y = x[currentTab].getElementsByTagName("input");
    // A loop that checks every input field in the current tab:
    for (i = 0; i < y.length; i++) {
      // If a field is empty...
      if (y[i].value == "") {
        // add an "invalid" class to the field:
        y[i].className += " invalid";
        // and set the current valid status to false
        valid = false;
      }
    }
    // If the valid status is true, mark the step as finished and valid:
    if (valid) {
      document.getElementsByClassName("stepIndicator")[currentTab].className +=
        " finish";
    }
    return valid; // return the valid status
  }

  function fixStepIndicator(n) {
    // This function removes the "active" class of all steps...
    var i,
      x = document.getElementsByClassName("stepIndicator");
    for (i = 0; i < x.length; i++) {
      x[i].className = x[i].className.replace(" active", "");
    }
    //... and adds the "active" class on the current step:
    x[n].className += " active";
  }

  

  $(".select-province").on('change',function(){
    $.ajax({
      type: 'GET',
      dataType: 'script',
      url: '/members/districts',
      data: {id: $(this).val()},
    });
  });

  $("#prevBtn").on('click', function() {
    if (currentTab == 0 && $('.cnic-alert').text() == '') {
      $("#nextBtn").prop('disabled', false);
    }
  })

  $("#nextBtn").on('click', function() {
    if (currentTab == 1) {
      if ($("#local_govt_structure_id").val() != '' && $("#province").val() != '' && $("#district").val() != '' ) {
        if ($('#unit').length > 0 && $("#local_govt_structure_id").val() != '') {
          if ($('#unit').val() != '') {
            $("#nextBtn").prop('disabled', false);
          }
          else {
            $("#nextBtn").prop('disabled', true); 
          }
        }
        else if ($('#unit').length == 0) {
          $("#nextBtn").prop('disabled', false); 
        }
        else {
          $("#nextBtn").prop('disabled', true); 
        }
      }
      else {
        $("#nextBtn").prop('disabled', true); 
      }
    }
  })


</script>

app/views/members/units.js.erb
<% if @units != nil %>
	<% if @units.count > 0 %>
		$('#area_unit').html("<%= escape_javascript(render partial: 'units', locals: { units: @units } ) %>")
		$("#nextBtn").prop('disabled', true);
	<% else %>
		$('#area_unit').html("<%= escape_javascript(render partial: 'empty_partial', locals: { units: @units } ) %>")
		$("#nextBtn").prop('disabled', false);
	<% end %>
<% else %>
	$('#area_unit').html("<%= escape_javascript(render partial: 'empty_unit' ) %>")
	$("#nextBtn").prop('disabled', true);
<% end %>

$(".select-unit").on('change',function(){
	if ($(this).val() == '') {
		$("#nextBtn").prop('disabled', true);
	}
	else {
		$("#nextBtn").prop('disabled', false);	
	}

});